name: C/C++ CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc

    - name: Compile tests
      run: gcc -o run_tests tests/*.c -lm -DCLUT_OUTPUT_GITHUB

    - name: Run tests
      run: ./run_tests
