name: C/C++ CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc

    - name: Compile runner generator
      run: gcc -o runner_generator tools/runner_generator.c

    - name: Generate test runner
      run: ./runner_generator -o tests/runner_test_clut.c tests/test_basic.h tests/test_numeric.h tests/test_string.h tests/test_arrays.h

    - name: Compile test runner
      run: gcc -o tests/runner_test_clut tests/runner_test_clut.c -DCLUT_OUTPUT_GITHUB

    - name: Run tests
      run: ./tests/runner_test_clut
